local bufnr = vim.api.nvim_create_buf(false, true)
vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, {"line1", "line2", "line3"})
local ns = vim.api.nvim_create_namespace("test")
-- set extmark at row 1 (line2)
local m1 = vim.api.nvim_buf_set_extmark(bufnr, ns, 1, 0, {})
vim.api.nvim_win_set_buf(0, bufnr)
vim.api.nvim_win_set_cursor(0, {2, 0})
vim.cmd("normal! ddO")
local marks = vim.api.nvim_buf_get_extmarks(bufnr, ns, 0, -1, {})
print("Mark after ddO:", marks[1][2])
